// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_sequences.sql

package sqlcgen

import (
	"context"
)

const currentSeq = `-- name: CurrentSeq :one
SELECT current_seq FROM account_sequences WHERE account_id = $1
`

func (q *Queries) CurrentSeq(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentSeq, accountID)
	var current_seq int64
	err := row.Scan(&current_seq)
	return current_seq, err
}

const insertAccountSequenceRow = `-- name: InsertAccountSequenceRow :exec
INSERT INTO account_sequences (account_id, current_seq) VALUES ($1, 0)
`

func (q *Queries) InsertAccountSequenceRow(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, insertAccountSequenceRow, accountID)
	return err
}

const nextSeq = `-- name: NextSeq :one
UPDATE account_sequences SET current_seq = current_seq + 1 WHERE account_id = $1 RETURNING current_seq
`

func (q *Queries) NextSeq(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSeq, accountID)
	var current_seq int64
	err := row.Scan(&current_seq)
	return current_seq, err
}
