// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const accountByEmail = `-- name: AccountByEmail :one
SELECT id, email, name, timezone, email_verified, password_hash
FROM accounts
WHERE email = $1
`

type AccountByEmailRow struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Timezone      string         `json:"timezone"`
	EmailVerified bool           `json:"email_verified"`
	PasswordHash  []byte         `json:"password_hash"`
}

func (q *Queries) AccountByEmail(ctx context.Context, email string) (AccountByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, accountByEmail, email)
	var i AccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.EmailVerified,
		&i.PasswordHash,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
SELECT id, email, name, timezone, email_verified, password_hash
FROM accounts
WHERE id = $1
`

type AccountByIDRow struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Timezone      string         `json:"timezone"`
	EmailVerified bool           `json:"email_verified"`
	PasswordHash  []byte         `json:"password_hash"`
}

func (q *Queries) AccountByID(ctx context.Context, id string) (AccountByIDRow, error) {
	row := q.db.QueryRowContext(ctx, accountByID, id)
	var i AccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.EmailVerified,
		&i.PasswordHash,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, email, name, timezone, email_verified, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAccountParams struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Timezone      string         `json:"timezone"`
	EmailVerified bool           `json:"email_verified"`
	PasswordHash  []byte         `json:"password_hash"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Timezone,
		arg.EmailVerified,
		arg.PasswordHash,
	)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE accounts SET email_verified = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE accounts SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetPasswordParams struct {
	ID           string `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setPassword, arg.ID, arg.PasswordHash)
	return err
}
