// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: change_feed.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertChange = `-- name: InsertChange :exec
INSERT INTO change_feed (account_id, server_seq, entity_type, entity_id, operation, payload, received_at_server)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertChangeParams struct {
	AccountID        string    `json:"account_id"`
	ServerSeq        int64     `json:"server_seq"`
	EntityType       string    `json:"entity_type"`
	EntityID         string    `json:"entity_id"`
	Operation        string    `json:"operation"`
	Payload          []byte    `json:"payload"`
	ReceivedAtServer time.Time `json:"received_at_server"`
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) error {
	_, err := q.db.ExecContext(ctx, insertChange,
		arg.AccountID,
		arg.ServerSeq,
		arg.EntityType,
		arg.EntityID,
		arg.Operation,
		arg.Payload,
		arg.ReceivedAtServer,
	)
	return err
}

const listChangesInRange = `-- name: ListChangesInRange :many
SELECT server_seq, entity_type, entity_id, operation, payload, received_at_server
FROM change_feed
WHERE account_id = $1 AND server_seq > $2 AND server_seq <= $3
ORDER BY server_seq ASC
LIMIT $4
`

type ListChangesInRangeParams struct {
	AccountID   string `json:"account_id"`
	ServerSeq   int64  `json:"server_seq"`
	ServerSeq_2 int64  `json:"server_seq_2"`
	Limit       int32  `json:"limit"`
}

type ListChangesInRangeRow struct {
	ServerSeq        int64     `json:"server_seq"`
	EntityType       string    `json:"entity_type"`
	EntityID         string    `json:"entity_id"`
	Operation        string    `json:"operation"`
	Payload          []byte    `json:"payload"`
	ReceivedAtServer time.Time `json:"received_at_server"`
}

func (q *Queries) ListChangesInRange(ctx context.Context, arg ListChangesInRangeParams) ([]ListChangesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangesInRange,
		arg.AccountID,
		arg.ServerSeq,
		arg.ServerSeq_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangesInRangeRow
	for rows.Next() {
		var i ListChangesInRangeRow
		if err := rows.Scan(
			&i.ServerSeq,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.Payload,
			&i.ReceivedAtServer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
