// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package sqlcgen

import (
	"context"
	"time"
)

const deviceRegistered = `-- name: DeviceRegistered :one
SELECT EXISTS (
    SELECT 1 FROM devices WHERE account_id = $1 AND device_id = $2
)
`

type DeviceRegisteredParams struct {
	AccountID string `json:"account_id"`
	DeviceID  string `json:"device_id"`
}

func (q *Queries) DeviceRegistered(ctx context.Context, arg DeviceRegisteredParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, deviceRegistered, arg.AccountID, arg.DeviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findDeviceRegisteredAt = `-- name: FindDeviceRegisteredAt :one
SELECT registered_at FROM devices WHERE account_id = $1 AND device_id = $2
`

type FindDeviceRegisteredAtParams struct {
	AccountID string `json:"account_id"`
	DeviceID  string `json:"device_id"`
}

func (q *Queries) FindDeviceRegisteredAt(ctx context.Context, arg FindDeviceRegisteredAtParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, findDeviceRegisteredAt, arg.AccountID, arg.DeviceID)
	var registered_at time.Time
	err := row.Scan(&registered_at)
	return registered_at, err
}

const registerDeviceIfAbsent = `-- name: RegisterDeviceIfAbsent :one
INSERT INTO devices (account_id, device_id, registered_at)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, device_id) DO NOTHING
RETURNING registered_at
`

type RegisterDeviceIfAbsentParams struct {
	AccountID    string    `json:"account_id"`
	DeviceID     string    `json:"device_id"`
	RegisteredAt time.Time `json:"registered_at"`
}

// Atomic insert-if-absent: returns the row only when this call created it.
// When it returns sql.ErrNoRows, the device was already registered and the
// caller must look up its original registered_at with FindDeviceRegisteredAt.
func (q *Queries) RegisterDeviceIfAbsent(ctx context.Context, arg RegisterDeviceIfAbsentParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, registerDeviceIfAbsent, arg.AccountID, arg.DeviceID, arg.RegisteredAt)
	var registered_at time.Time
	err := row.Scan(&registered_at)
	return registered_at, err
}
