// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fuel_logs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const findFuelLog = `-- name: FindFuelLog :one
SELECT server_seq, received_at_server FROM fuel_logs WHERE account_id = $1 AND id = $2
`

type FindFuelLogParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

type FindFuelLogRow struct {
	ServerSeq        int64     `json:"server_seq"`
	ReceivedAtServer time.Time `json:"received_at_server"`
}

// A sql.ErrNoRows result means this append-only log has not been applied
// yet (not a duplicate).
func (q *Queries) FindFuelLog(ctx context.Context, arg FindFuelLogParams) (FindFuelLogRow, error) {
	row := q.db.QueryRowContext(ctx, findFuelLog, arg.AccountID, arg.ID)
	var i FindFuelLogRow
	err := row.Scan(&i.ServerSeq, &i.ReceivedAtServer)
	return i, err
}

const fuelLogExists = `-- name: FuelLogExists :one
SELECT EXISTS (
    SELECT 1 FROM fuel_logs WHERE account_id = $1 AND id = $2
)
`

type FuelLogExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) FuelLogExists(ctx context.Context, arg FuelLogExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fuelLogExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertFuelLog = `-- name: InsertFuelLog :exec
INSERT INTO fuel_logs (account_id, id, vehicle_id, recorded_at, liters, cost_vnd, shop, note, odometer_log_id, is_full_tank, server_seq, received_at_server)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertFuelLogParams struct {
	AccountID        string         `json:"account_id"`
	ID               string         `json:"id"`
	VehicleID        string         `json:"vehicle_id"`
	RecordedAt       time.Time      `json:"recorded_at"`
	Liters           sql.NullString `json:"liters"`
	CostVnd          sql.NullInt64  `json:"cost_vnd"`
	Shop             sql.NullString `json:"shop"`
	Note             sql.NullString `json:"note"`
	OdometerLogID    *string        `json:"odometer_log_id"`
	IsFullTank       bool           `json:"is_full_tank"`
	ServerSeq        int64          `json:"server_seq"`
	ReceivedAtServer time.Time      `json:"received_at_server"`
}

func (q *Queries) InsertFuelLog(ctx context.Context, arg InsertFuelLogParams) error {
	_, err := q.db.ExecContext(ctx, insertFuelLog,
		arg.AccountID,
		arg.ID,
		arg.VehicleID,
		arg.RecordedAt,
		arg.Liters,
		arg.CostVnd,
		arg.Shop,
		arg.Note,
		arg.OdometerLogID,
		arg.IsFullTank,
		arg.ServerSeq,
		arg.ReceivedAtServer,
	)
	return err
}
