// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel_logs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const canonicalFuelLogPayload = `-- name: CanonicalFuelLogPayload :one
SELECT jsonb_build_object(
    'vehicle_id', vehicle_id,
    'recorded_at', recorded_at,
    'liters', liters,
    'cost', cost,
    'note', note,
    'odometer_log_id', odometer_log_id,
    'is_full_tank', is_full_tank,
    'deleted_at', deleted_at
)
FROM fuel_logs
WHERE account_id = $1 AND id = $2
`

type CanonicalFuelLogPayloadParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) CanonicalFuelLogPayload(ctx context.Context, arg CanonicalFuelLogPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, canonicalFuelLogPayload, arg.AccountID, arg.ID)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const fuelLogExists = `-- name: FuelLogExists :one
SELECT EXISTS (
    SELECT 1 FROM fuel_logs WHERE account_id = $1 AND id = $2
)
`

type FuelLogExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) FuelLogExists(ctx context.Context, arg FuelLogExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fuelLogExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockFuelLogForUpdate = `-- name: LockFuelLogForUpdate :one
SELECT server_seq FROM fuel_logs WHERE account_id = $1 AND id = $2 FOR UPDATE
`

type LockFuelLogForUpdateParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

// Row lock used to serialize concurrent mutations of the same fuel log. A
// sql.ErrNoRows result means the log has no current snapshot yet.
func (q *Queries) LockFuelLogForUpdate(ctx context.Context, arg LockFuelLogForUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockFuelLogForUpdate, arg.AccountID, arg.ID)
	var server_seq int64
	err := row.Scan(&server_seq)
	return server_seq, err
}

const upsertFuelLog = `-- name: UpsertFuelLog :exec
INSERT INTO fuel_logs (account_id, id, vehicle_id, recorded_at, liters, cost, note, odometer_log_id, is_full_tank, deleted_at, server_seq, server_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (account_id, id) DO UPDATE
  SET vehicle_id = EXCLUDED.vehicle_id,
      recorded_at = EXCLUDED.recorded_at,
      liters = EXCLUDED.liters,
       cost = EXCLUDED.cost,
      note = EXCLUDED.note,
      odometer_log_id = EXCLUDED.odometer_log_id,
      is_full_tank = EXCLUDED.is_full_tank,
      deleted_at = EXCLUDED.deleted_at,
      server_seq = EXCLUDED.server_seq,
       server_synced_at = EXCLUDED.server_synced_at
`

type UpsertFuelLogParams struct {
	AccountID      string         `json:"account_id"`
	ID             string         `json:"id"`
	VehicleID      string         `json:"vehicle_id"`
	RecordedAt     time.Time      `json:"recorded_at"`
	Liters         sql.NullString `json:"liters"`
	Cost           sql.NullString `json:"cost"`
	Note           sql.NullString `json:"note"`
	OdometerLogID  *string        `json:"odometer_log_id"`
	IsFullTank     bool           `json:"is_full_tank"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ServerSeq      int64          `json:"server_seq"`
	ServerSyncedAt time.Time      `json:"server_synced_at"`
}

func (q *Queries) UpsertFuelLog(ctx context.Context, arg UpsertFuelLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertFuelLog,
		arg.AccountID,
		arg.ID,
		arg.VehicleID,
		arg.RecordedAt,
		arg.Liters,
		arg.Cost,
		arg.Note,
		arg.OdometerLogID,
		arg.IsFullTank,
		arg.DeletedAt,
		arg.ServerSeq,
		arg.ServerSyncedAt,
	)
	return err
}
