// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Timezone      string         `json:"timezone"`
	EmailVerified bool           `json:"email_verified"`
	PasswordHash  []byte         `json:"password_hash"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type AccountSequence struct {
	AccountID  string `json:"account_id"`
	CurrentSeq int64  `json:"current_seq"`
}

type ChangeFeed struct {
	ID             int64     `json:"id"`
	AccountID      string    `json:"account_id"`
	EntityID       string    `json:"entity_id"`
	EntityType     string    `json:"entity_type"`
	ServerSeq      int64     `json:"server_seq"`
	Operation      string    `json:"operation"`
	Payload        []byte    `json:"payload"`
	ServerSyncedAt time.Time `json:"server_synced_at"`
}

type Device struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	Metadata     []byte         `json:"metadata"`
	AppVersion   sql.NullString `json:"app_version"`
	RegisteredAt time.Time      `json:"registered_at"`
	LastSeenAt   sql.NullTime   `json:"last_seen_at"`
}

type FuelLog struct {
	ID             string         `json:"id"`
	AccountID      string         `json:"account_id"`
	VehicleID      string         `json:"vehicle_id"`
	OdometerLogID  *string        `json:"odometer_log_id"`
	RecordedAt     time.Time      `json:"recorded_at"`
	Liters         sql.NullString `json:"liters"`
	Cost           sql.NullString `json:"cost"`
	Note           sql.NullString `json:"note"`
	IsFullTank     bool           `json:"is_full_tank"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ServerSeq      int64          `json:"server_seq"`
	ServerSyncedAt time.Time      `json:"server_synced_at"`
}

type OdometerLog struct {
	ID             string         `json:"id"`
	AccountID      string         `json:"account_id"`
	VehicleID      string         `json:"vehicle_id"`
	OdometerKm     string         `json:"odometer_km"`
	RecordedAt     time.Time      `json:"recorded_at"`
	Source         string         `json:"source"`
	Note           sql.NullString `json:"note"`
	ServerSeq      int64          `json:"server_seq"`
	ServerSyncedAt time.Time      `json:"server_synced_at"`
}

type PartType struct {
	ID             string    `json:"id"`
	AccountID      string    `json:"account_id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	DisplayOrder   int32     `json:"display_order"`
	Active         bool      `json:"active"`
	ServerSeq      int64     `json:"server_seq"`
	ServerSyncedAt time.Time `json:"server_synced_at"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ProcessedMutation struct {
	AccountID      string         `json:"account_id"`
	DeviceID       string         `json:"device_id"`
	MutationID     string         `json:"mutation_id"`
	EntityType     string         `json:"entity_type"`
	EntityID       string         `json:"entity_id"`
	Status         string         `json:"status"`
	ServerSeq      sql.NullInt64  `json:"server_seq"`
	ServerSyncedAt sql.NullTime   `json:"server_synced_at"`
	ErrorCode      sql.NullString `json:"error_code"`
	ErrorMessage   sql.NullString `json:"error_message"`
	Retryable      sql.NullBool   `json:"retryable"`
	ServerSnapshot []byte         `json:"server_snapshot"`
	CreatedAt      time.Time      `json:"created_at"`
}

type ReminderConfig struct {
	ID                 string         `json:"id"`
	AccountID          string         `json:"account_id"`
	VehicleID          string         `json:"vehicle_id"`
	PartTypeID         string         `json:"part_type_id"`
	IntervalKm         sql.NullString `json:"interval_km"`
	IntervalDays       sql.NullInt32  `json:"interval_days"`
	BaselineOdometerKm sql.NullString `json:"baseline_odometer_km"`
	BaselineDate       sql.NullTime   `json:"baseline_date"`
	Enabled            bool           `json:"enabled"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	ServerSeq          int64          `json:"server_seq"`
	ServerSyncedAt     time.Time      `json:"server_synced_at"`
}

type ReminderNotification struct {
	ID               int64          `json:"id"`
	AccountID        string         `json:"account_id"`
	VehicleID        string         `json:"vehicle_id"`
	ReminderConfigID string         `json:"reminder_config_id"`
	IdempotencyKey   string         `json:"idempotency_key"`
	Status           string         `json:"status"`
	AttemptedAt      time.Time      `json:"attempted_at"`
	SentAt           sql.NullTime   `json:"sent_at"`
	ErrorMessage     sql.NullString `json:"error_message"`
}

type ServiceLog struct {
	ID                 string         `json:"id"`
	AccountID          string         `json:"account_id"`
	VehicleID          string         `json:"vehicle_id"`
	PartTypeID         string         `json:"part_type_id"`
	ServicedAt         time.Time      `json:"serviced_at"`
	OdometerKmSnapshot sql.NullString `json:"odometer_km_snapshot"`
	Cost               sql.NullString `json:"cost"`
	Note               sql.NullString `json:"note"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	ServerSeq          int64          `json:"server_seq"`
	ServerSyncedAt     time.Time      `json:"server_synced_at"`
}

type Vehicle struct {
	ID             string         `json:"id"`
	AccountID      string         `json:"account_id"`
	Name           string         `json:"name"`
	PlateNumber    sql.NullString `json:"plate_number"`
	ArchivedAt     sql.NullTime   `json:"archived_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	DueSoonRatio   sql.NullString `json:"due_soon_ratio"`
	ServerSeq      int64          `json:"server_seq"`
	ServerSyncedAt time.Time      `json:"server_synced_at"`
}
