// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: odometer_logs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const canonicalOdometerLogPayload = `-- name: CanonicalOdometerLogPayload :one
SELECT jsonb_build_object(
    'vehicle_id', vehicle_id,
    'odometer_km', odometer_km,
    'recorded_at', recorded_at,
    'source', source,
    'note', note
)
FROM odometer_logs
WHERE account_id = $1 AND id = $2
`

type CanonicalOdometerLogPayloadParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) CanonicalOdometerLogPayload(ctx context.Context, arg CanonicalOdometerLogPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, canonicalOdometerLogPayload, arg.AccountID, arg.ID)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const findOdometerLog = `-- name: FindOdometerLog :one
SELECT server_seq, server_synced_at FROM odometer_logs WHERE account_id = $1 AND id = $2
`

type FindOdometerLogParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

type FindOdometerLogRow struct {
	ServerSeq      int64     `json:"server_seq"`
	ServerSyncedAt time.Time `json:"server_synced_at"`
}

// A sql.ErrNoRows result means this append-only log has not been applied
// yet (not a duplicate).
func (q *Queries) FindOdometerLog(ctx context.Context, arg FindOdometerLogParams) (FindOdometerLogRow, error) {
	row := q.db.QueryRowContext(ctx, findOdometerLog, arg.AccountID, arg.ID)
	var i FindOdometerLogRow
	err := row.Scan(&i.ServerSeq, &i.ServerSyncedAt)
	return i, err
}

const insertOdometerLog = `-- name: InsertOdometerLog :exec
INSERT INTO odometer_logs (account_id, id, vehicle_id, odometer_km, recorded_at, source, note, server_seq, server_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertOdometerLogParams struct {
	AccountID      string         `json:"account_id"`
	ID             string         `json:"id"`
	VehicleID      string         `json:"vehicle_id"`
	OdometerKm     string         `json:"odometer_km"`
	RecordedAt     time.Time      `json:"recorded_at"`
	Source         string         `json:"source"`
	Note           sql.NullString `json:"note"`
	ServerSeq      int64          `json:"server_seq"`
	ServerSyncedAt time.Time      `json:"server_synced_at"`
}

func (q *Queries) InsertOdometerLog(ctx context.Context, arg InsertOdometerLogParams) error {
	_, err := q.db.ExecContext(ctx, insertOdometerLog,
		arg.AccountID,
		arg.ID,
		arg.VehicleID,
		arg.OdometerKm,
		arg.RecordedAt,
		arg.Source,
		arg.Note,
		arg.ServerSeq,
		arg.ServerSyncedAt,
	)
	return err
}

const odometerLogExists = `-- name: OdometerLogExists :one
SELECT EXISTS (
    SELECT 1 FROM odometer_logs WHERE account_id = $1 AND id = $2
)
`

type OdometerLogExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) OdometerLogExists(ctx context.Context, arg OdometerLogExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, odometerLogExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
