// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: part_types.sql

package sqlcgen

import (
	"context"
	"time"
)

const canonicalPartTypePayload = `-- name: CanonicalPartTypePayload :one
SELECT jsonb_build_object(
    'code', code,
    'name', name,
    'display_order', display_order,
    'active', active
)
FROM part_types
WHERE account_id = $1 AND id = $2
`

type CanonicalPartTypePayloadParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) CanonicalPartTypePayload(ctx context.Context, arg CanonicalPartTypePayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, canonicalPartTypePayload, arg.AccountID, arg.ID)
	var jsonb_build_object []byte
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const listPartTypes = `-- name: ListPartTypes :many
SELECT id, code, name, display_order, active, account_id, server_seq, server_synced_at
FROM part_types
WHERE account_id = $1
ORDER BY display_order, created_at
`

type ListPartTypesRow struct {
	ID             string    `json:"id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	DisplayOrder   int32     `json:"display_order"`
	Active         bool      `json:"active"`
	AccountID      string    `json:"account_id"`
	ServerSeq      int64     `json:"server_seq"`
	ServerSyncedAt time.Time `json:"server_synced_at"`
}

// This account's own part_types rows (seeded at signup plus anything it
// added itself); seeded rows sort first by display_order, custom rows after
// in creation order (display_order is a fixed constant for custom rows, see
// buildUpsertPartTypeParams). Includes server_seq/server_synced_at so the
// client can learn the real server_seq for a bootstrapped row instead of
// treating it as "never seen from server" (see domain.PartType doc comment).
func (q *Queries) ListPartTypes(ctx context.Context, accountID string) ([]ListPartTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartTypes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartTypesRow
	for rows.Next() {
		var i ListPartTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DisplayOrder,
			&i.Active,
			&i.AccountID,
			&i.ServerSeq,
			&i.ServerSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPartTypeForUpdate = `-- name: LockPartTypeForUpdate :one
SELECT server_seq FROM part_types WHERE account_id = $1 AND id = $2 FOR UPDATE
`

type LockPartTypeForUpdateParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

// Row lock scoped to THIS account — a sql.ErrNoRows result means either the
// row doesn't exist yet, or it exists but is a global/other-account row this
// account cannot mutate (validateMutation rejects that case separately with
// ownership_invalid before this is reached for "update").
func (q *Queries) LockPartTypeForUpdate(ctx context.Context, arg LockPartTypeForUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockPartTypeForUpdate, arg.AccountID, arg.ID)
	var server_seq int64
	err := row.Scan(&server_seq)
	return server_seq, err
}

const partTypeActiveForAccount = `-- name: PartTypeActiveForAccount :one
SELECT EXISTS (
    SELECT 1 FROM part_types WHERE id = $1 AND account_id = $2 AND active
)
`

type PartTypeActiveForAccountParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) PartTypeActiveForAccount(ctx context.Context, arg PartTypeActiveForAccountParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, partTypeActiveForAccount, arg.ID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const partTypeOwnedByAccount = `-- name: PartTypeOwnedByAccount :one
SELECT EXISTS (
    SELECT 1 FROM part_types WHERE id = $1 AND account_id = $2
)
`

type PartTypeOwnedByAccountParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) PartTypeOwnedByAccount(ctx context.Context, arg PartTypeOwnedByAccountParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, partTypeOwnedByAccount, arg.ID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPartType = `-- name: UpsertPartType :execrows
INSERT INTO part_types (id, account_id, code, name, display_order, active, server_seq, server_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name,
      active = EXCLUDED.active,
      server_seq = EXCLUDED.server_seq,
       server_synced_at = EXCLUDED.server_synced_at
  WHERE part_types.account_id = EXCLUDED.account_id
`

type UpsertPartTypeParams struct {
	ID             string    `json:"id"`
	AccountID      string    `json:"account_id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	DisplayOrder   int32     `json:"display_order"`
	Active         bool      `json:"active"`
	ServerSeq      int64     `json:"server_seq"`
	ServerSyncedAt time.Time `json:"server_synced_at"`
}

func (q *Queries) UpsertPartType(ctx context.Context, arg UpsertPartTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertPartType,
		arg.ID,
		arg.AccountID,
		arg.Code,
		arg.Name,
		arg.DisplayOrder,
		arg.Active,
		arg.ServerSeq,
		arg.ServerSyncedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
