// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed_mutations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const findProcessedMutationForUpdate = `-- name: FindProcessedMutationForUpdate :one
SELECT entity_type, entity_id, status, server_seq, received_at_server, error_code, error_message, retryable, server_snapshot
FROM processed_mutations
WHERE account_id = $1 AND device_id = $2 AND mutation_id = $3
FOR UPDATE
`

type FindProcessedMutationForUpdateParams struct {
	AccountID  string `json:"account_id"`
	DeviceID   string `json:"device_id"`
	MutationID string `json:"mutation_id"`
}

type FindProcessedMutationForUpdateRow struct {
	EntityType       string         `json:"entity_type"`
	EntityID         string         `json:"entity_id"`
	Status           string         `json:"status"`
	ServerSeq        sql.NullInt64  `json:"server_seq"`
	ReceivedAtServer sql.NullTime   `json:"received_at_server"`
	ErrorCode        sql.NullString `json:"error_code"`
	ErrorMessage     sql.NullString `json:"error_message"`
	Retryable        sql.NullBool   `json:"retryable"`
	ServerSnapshot   []byte         `json:"server_snapshot"`
}

func (q *Queries) FindProcessedMutationForUpdate(ctx context.Context, arg FindProcessedMutationForUpdateParams) (FindProcessedMutationForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, findProcessedMutationForUpdate, arg.AccountID, arg.DeviceID, arg.MutationID)
	var i FindProcessedMutationForUpdateRow
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Status,
		&i.ServerSeq,
		&i.ReceivedAtServer,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.ServerSnapshot,
	)
	return i, err
}

const insertProcessedMutation = `-- name: InsertProcessedMutation :exec
INSERT INTO processed_mutations (
    account_id, device_id, mutation_id, entity_type, entity_id, status,
    server_seq, received_at_server, error_code, error_message, retryable, server_snapshot
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertProcessedMutationParams struct {
	AccountID        string         `json:"account_id"`
	DeviceID         string         `json:"device_id"`
	MutationID       string         `json:"mutation_id"`
	EntityType       string         `json:"entity_type"`
	EntityID         string         `json:"entity_id"`
	Status           string         `json:"status"`
	ServerSeq        sql.NullInt64  `json:"server_seq"`
	ReceivedAtServer sql.NullTime   `json:"received_at_server"`
	ErrorCode        sql.NullString `json:"error_code"`
	ErrorMessage     sql.NullString `json:"error_message"`
	Retryable        sql.NullBool   `json:"retryable"`
	ServerSnapshot   []byte         `json:"server_snapshot"`
}

func (q *Queries) InsertProcessedMutation(ctx context.Context, arg InsertProcessedMutationParams) error {
	_, err := q.db.ExecContext(ctx, insertProcessedMutation,
		arg.AccountID,
		arg.DeviceID,
		arg.MutationID,
		arg.EntityType,
		arg.EntityID,
		arg.Status,
		arg.ServerSeq,
		arg.ReceivedAtServer,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Retryable,
		arg.ServerSnapshot,
	)
	return err
}
