// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pull_watermarks.sql

package sqlcgen

import (
	"context"
	"time"
)

const cleanupExpiredWatermarks = `-- name: CleanupExpiredWatermarks :exec
DELETE FROM pull_watermarks WHERE account_id = $1 AND expires_at <= $2
`

type CleanupExpiredWatermarksParams struct {
	AccountID string    `json:"account_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CleanupExpiredWatermarks(ctx context.Context, arg CleanupExpiredWatermarksParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredWatermarks, arg.AccountID, arg.ExpiresAt)
	return err
}

const findWatermark = `-- name: FindWatermark :one
SELECT upper_bound, expires_at FROM pull_watermarks WHERE account_id = $1 AND token = $2
`

type FindWatermarkParams struct {
	AccountID string `json:"account_id"`
	Token     string `json:"token"`
}

type FindWatermarkRow struct {
	UpperBound int64     `json:"upper_bound"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) FindWatermark(ctx context.Context, arg FindWatermarkParams) (FindWatermarkRow, error) {
	row := q.db.QueryRowContext(ctx, findWatermark, arg.AccountID, arg.Token)
	var i FindWatermarkRow
	err := row.Scan(&i.UpperBound, &i.ExpiresAt)
	return i, err
}

const mintWatermark = `-- name: MintWatermark :exec
INSERT INTO pull_watermarks (account_id, token, upper_bound, expires_at)
VALUES ($1, $2, $3, $4)
`

type MintWatermarkParams struct {
	AccountID  string    `json:"account_id"`
	Token      string    `json:"token"`
	UpperBound int64     `json:"upper_bound"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) MintWatermark(ctx context.Context, arg MintWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, mintWatermark,
		arg.AccountID,
		arg.Token,
		arg.UpperBound,
		arg.ExpiresAt,
	)
	return err
}
