// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reminder_configs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const findActiveReminderScopeOwner = `-- name: FindActiveReminderScopeOwner :one
SELECT id FROM reminder_configs
WHERE account_id = $1 AND vehicle_id = $2 AND part_type_id = $3 AND deleted_at IS NULL AND id <> $4
LIMIT 1
`

type FindActiveReminderScopeOwnerParams struct {
	AccountID  string `json:"account_id"`
	VehicleID  string `json:"vehicle_id"`
	PartTypeID string `json:"part_type_id"`
	ID         string `json:"id"`
}

// Pre-check for the D7 uniqueness rule: an active (non-deleted) reminder
// already owns this (vehicle_id, part_type_id) scope, and it is not the
// entity currently being mutated.
func (q *Queries) FindActiveReminderScopeOwner(ctx context.Context, arg FindActiveReminderScopeOwnerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findActiveReminderScopeOwner,
		arg.AccountID,
		arg.VehicleID,
		arg.PartTypeID,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockReminderConfigForUpdate = `-- name: LockReminderConfigForUpdate :one
SELECT server_seq FROM reminder_configs WHERE account_id = $1 AND id = $2 FOR UPDATE
`

type LockReminderConfigForUpdateParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

// Row lock used to serialize concurrent mutations of the same reminder
// config. A sql.ErrNoRows result means it has no current snapshot yet.
func (q *Queries) LockReminderConfigForUpdate(ctx context.Context, arg LockReminderConfigForUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockReminderConfigForUpdate, arg.AccountID, arg.ID)
	var server_seq int64
	err := row.Scan(&server_seq)
	return server_seq, err
}

const reminderConfigExists = `-- name: ReminderConfigExists :one
SELECT EXISTS (
    SELECT 1 FROM reminder_configs WHERE account_id = $1 AND id = $2
)
`

type ReminderConfigExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) ReminderConfigExists(ctx context.Context, arg ReminderConfigExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reminderConfigExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const canonicalReminderConfigPayload = `-- name: CanonicalReminderConfigPayload :one
SELECT jsonb_build_object(
    'vehicle_id', vehicle_id,
    'part_type_id', part_type_id,
    'interval_km', interval_km,
    'interval_days', interval_days,
    'baseline_odometer_km', baseline_odometer_km,
    'baseline_date', baseline_date,
    'enabled', enabled,
    'deleted_at', deleted_at
)
FROM reminder_configs
WHERE account_id = $1 AND id = $2
`

type CanonicalReminderConfigPayloadParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) CanonicalReminderConfigPayload(ctx context.Context, arg CanonicalReminderConfigPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, canonicalReminderConfigPayload, arg.AccountID, arg.ID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const reminderConfigUsesPartType = `-- name: ReminderConfigUsesPartType :one
SELECT EXISTS (
    SELECT 1 FROM reminder_configs WHERE account_id = $1 AND id = $2 AND part_type_id = $3
)
`

type ReminderConfigUsesPartTypeParams struct {
	AccountID  string `json:"account_id"`
	ID         string `json:"id"`
	PartTypeID string `json:"part_type_id"`
}

func (q *Queries) ReminderConfigUsesPartType(ctx context.Context, arg ReminderConfigUsesPartTypeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reminderConfigUsesPartType, arg.AccountID, arg.ID, arg.PartTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertReminderConfig = `-- name: UpsertReminderConfig :exec
INSERT INTO reminder_configs (
    account_id, id, vehicle_id, part_type_id, interval_km, interval_days,
    baseline_odometer_km, baseline_date, enabled, deleted_at, server_seq, received_at_server
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (account_id, id) DO UPDATE
  SET vehicle_id = EXCLUDED.vehicle_id,
      part_type_id = EXCLUDED.part_type_id,
      interval_km = EXCLUDED.interval_km,
      interval_days = EXCLUDED.interval_days,
      baseline_odometer_km = EXCLUDED.baseline_odometer_km,
      baseline_date = EXCLUDED.baseline_date,
      enabled = EXCLUDED.enabled,
      deleted_at = EXCLUDED.deleted_at,
      server_seq = EXCLUDED.server_seq,
      received_at_server = EXCLUDED.received_at_server
`

type UpsertReminderConfigParams struct {
	AccountID          string         `json:"account_id"`
	ID                 string         `json:"id"`
	VehicleID          string         `json:"vehicle_id"`
	PartTypeID         string         `json:"part_type_id"`
	IntervalKm         sql.NullString `json:"interval_km"`
	IntervalDays       sql.NullInt32  `json:"interval_days"`
	BaselineOdometerKm sql.NullString `json:"baseline_odometer_km"`
	BaselineDate       sql.NullTime   `json:"baseline_date"`
	Enabled            bool           `json:"enabled"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	ServerSeq          int64          `json:"server_seq"`
	ReceivedAtServer   time.Time      `json:"received_at_server"`
}

func (q *Queries) UpsertReminderConfig(ctx context.Context, arg UpsertReminderConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertReminderConfig,
		arg.AccountID,
		arg.ID,
		arg.VehicleID,
		arg.PartTypeID,
		arg.IntervalKm,
		arg.IntervalDays,
		arg.BaselineOdometerKm,
		arg.BaselineDate,
		arg.Enabled,
		arg.DeletedAt,
		arg.ServerSeq,
		arg.ReceivedAtServer,
	)
	return err
}
