// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: service_logs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const findServiceLog = `-- name: FindServiceLog :one
SELECT server_seq, received_at_server FROM service_logs WHERE account_id = $1 AND id = $2
`

type FindServiceLogParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

type FindServiceLogRow struct {
	ServerSeq        int64     `json:"server_seq"`
	ReceivedAtServer time.Time `json:"received_at_server"`
}

// A sql.ErrNoRows result means this append-only log has not been applied
// yet (not a duplicate).
func (q *Queries) FindServiceLog(ctx context.Context, arg FindServiceLogParams) (FindServiceLogRow, error) {
	row := q.db.QueryRowContext(ctx, findServiceLog, arg.AccountID, arg.ID)
	var i FindServiceLogRow
	err := row.Scan(&i.ServerSeq, &i.ReceivedAtServer)
	return i, err
}

const insertServiceLog = `-- name: InsertServiceLog :exec
INSERT INTO service_logs (account_id, id, vehicle_id, part_type_id, serviced_at, odometer_km_snapshot, cost_vnd, note, server_seq, received_at_server)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertServiceLogParams struct {
	AccountID          string         `json:"account_id"`
	ID                 string         `json:"id"`
	VehicleID          string         `json:"vehicle_id"`
	PartTypeID         string         `json:"part_type_id"`
	ServicedAt         time.Time      `json:"serviced_at"`
	OdometerKmSnapshot sql.NullString `json:"odometer_km_snapshot"`
	CostVnd            sql.NullInt64  `json:"cost_vnd"`
	Note               sql.NullString `json:"note"`
	ServerSeq          int64          `json:"server_seq"`
	ReceivedAtServer   time.Time      `json:"received_at_server"`
}

func (q *Queries) InsertServiceLog(ctx context.Context, arg InsertServiceLogParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceLog,
		arg.AccountID,
		arg.ID,
		arg.VehicleID,
		arg.PartTypeID,
		arg.ServicedAt,
		arg.OdometerKmSnapshot,
		arg.CostVnd,
		arg.Note,
		arg.ServerSeq,
		arg.ReceivedAtServer,
	)
	return err
}

const serviceLogExists = `-- name: ServiceLogExists :one
SELECT EXISTS (
    SELECT 1 FROM service_logs WHERE account_id = $1 AND id = $2
)
`

type ServiceLogExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) ServiceLogExists(ctx context.Context, arg ServiceLogExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, serviceLogExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
