// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vehicles.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const lockVehicleForUpdate = `-- name: LockVehicleForUpdate :one
SELECT server_seq FROM vehicles WHERE account_id = $1 AND id = $2 FOR UPDATE
`

type LockVehicleForUpdateParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

// Row lock used to serialize concurrent mutations of the same vehicle. A
// sql.ErrNoRows result means the vehicle has no current snapshot yet.
func (q *Queries) LockVehicleForUpdate(ctx context.Context, arg LockVehicleForUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockVehicleForUpdate, arg.AccountID, arg.ID)
	var server_seq int64
	err := row.Scan(&server_seq)
	return server_seq, err
}

const upsertVehicle = `-- name: UpsertVehicle :exec
INSERT INTO vehicles (account_id, id, name, plate_number, archived_at, deleted_at, server_seq, received_at_server)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (account_id, id) DO UPDATE
  SET name = EXCLUDED.name,
      plate_number = EXCLUDED.plate_number,
      archived_at = EXCLUDED.archived_at,
      deleted_at = EXCLUDED.deleted_at,
      server_seq = EXCLUDED.server_seq,
      received_at_server = EXCLUDED.received_at_server
`

type UpsertVehicleParams struct {
	AccountID        string         `json:"account_id"`
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	PlateNumber      sql.NullString `json:"plate_number"`
	ArchivedAt       sql.NullTime   `json:"archived_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	ServerSeq        int64          `json:"server_seq"`
	ReceivedAtServer time.Time      `json:"received_at_server"`
}

func (q *Queries) UpsertVehicle(ctx context.Context, arg UpsertVehicleParams) error {
	_, err := q.db.ExecContext(ctx, upsertVehicle,
		arg.AccountID,
		arg.ID,
		arg.Name,
		arg.PlateNumber,
		arg.ArchivedAt,
		arg.DeletedAt,
		arg.ServerSeq,
		arg.ReceivedAtServer,
	)
	return err
}

const vehicleExists = `-- name: VehicleExists :one
SELECT EXISTS (
    SELECT 1 FROM vehicles WHERE account_id = $1 AND id = $2
)
`

type VehicleExistsParams struct {
	AccountID string `json:"account_id"`
	ID        string `json:"id"`
}

func (q *Queries) VehicleExists(ctx context.Context, arg VehicleExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, vehicleExists, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
