// Package seed defines the fixed part_types catalog and applies it
// idempotently.
package seed

// PartTypeSeed is one fixed catalog entry. ID and Code must never change
// once shipped; changing them would orphan reminder_configs and
// service_logs that already reference the row.
type PartTypeSeed struct {
	ID           string
	Code         string
	NameVI       string
	DisplayOrder int
	SeedVersion  string
}

// Manifest is the MVP part_types catalog approved in
// .docs/implementation-plan-section-5.md §7 (workstream C). UUIDs are fixed
// and must never be regenerated by a future run.
var Manifest = []PartTypeSeed{
	{ID: "649e41d9-00f8-4929-b343-407e4896060d", Code: "engine_oil", NameVI: "Dầu nhớt động cơ", DisplayOrder: 1, SeedVersion: "v1"},
	{ID: "33c46c84-d96c-4877-9328-a7975c971709", Code: "front_tire", NameVI: "Lốp trước", DisplayOrder: 2, SeedVersion: "v1"},
	{ID: "81c815e3-549f-4b20-91aa-d7545ad48b3d", Code: "rear_tire", NameVI: "Lốp sau", DisplayOrder: 3, SeedVersion: "v1"},
	{ID: "c8d6ed6d-ad5b-4134-8e9b-4966d5ece47e", Code: "front_brake_pad", NameVI: "Má phanh trước", DisplayOrder: 4, SeedVersion: "v1"},
	{ID: "e9d790b1-b366-45f1-9ba2-ff8420d35f6a", Code: "rear_brake_pad", NameVI: "Má phanh sau", DisplayOrder: 5, SeedVersion: "v1"},
	{ID: "ba3b91a3-1fe5-48b9-b8fd-3ac489c1b59d", Code: "spark_plug", NameVI: "Bugi", DisplayOrder: 6, SeedVersion: "v1"},
	{ID: "ff10d1fe-0757-4039-8ae2-ea8dae450a11", Code: "air_filter", NameVI: "Lọc gió", DisplayOrder: 7, SeedVersion: "v1"},
	{ID: "8e144e49-1dce-46ae-9bab-88435c25eb8d", Code: "drive_belt", NameVI: "Dây curoa", DisplayOrder: 8, SeedVersion: "v1"},
	{ID: "e7e3ca4e-12aa-4e8c-94c2-cfc198e78035", Code: "chain_sprocket_set", NameVI: "Nhông, sên, đĩa", DisplayOrder: 9, SeedVersion: "v1"},
	{ID: "16efa96d-4cc8-4b95-bf05-05255e9c49a4", Code: "battery", NameVI: "Ắc quy", DisplayOrder: 10, SeedVersion: "v1"},
}
